### ISSUE TITLE
Question how it will run on background

### ISSUE THREAD

**Issue by guicuton** [codespede/simple-multi-threader#1]
This is not a issues but an question.

This thread will be opened like nohup process on linux o.s?
if yes, the script will run as the same way if i do: "nohup php myscript.php" on linux terminal?

Thanks

**Comment by guicuton** [comment]
As i saw on src files the process will run as nohup...
Because of this i'll should enable shell_exec on my server.
This may be a little dangerous when enable this option isnt?

**Comment by codespede** [comment]
> This thread will be opened like nohup process on linux o.s?

Yes, it will start a nohup process in linux.

>if yes, the script will run as the same way if i do: "nohup php myscript.php" on linux terminal?

Correct

>Because of this i'll should enable shell_exec on my server.
>This may be a little dangerous when enable this option isnt?

Make sure your application is secure enough and validate each and every input. No PHP code should be allowed to run in your server without your intention. By this way you can avoid the danger it puts up(Please see also https://www.cmarix.com/how-to-secure-your-php-website-from-being-hacked/).

**Comment by kevmuret** [comment]
According a comment in php Manual the command is not running in background you can see a linux example : https://www.php.net/manual/fr/function.shell-exec.php#118495
And for windows : https://stackoverflow.com/questions/7692263/running-a-php-exec-in-the-background-on-windows

**Comment by codespede** [comment]
@kevmuret For linux, the command being executed is:
`php thread.php ...  > /dev/null 2>&1 &` which keeps the process running in the background as mentioned at https://www.php.net/manual/fr/function.shell-exec.php#118495

For Windows, thanks for pointing out, `shell_exec` is running in the foreground itself. `shell_exec` is now replaced with COM's WScript.Shell(https://github.com/codespede/simple-multi-threader/commit/d8832e4fa2c4c9e6ba199fa361b394aa5c4ae057)  for Windows with which, it's now confirmed that the process is running in the background itself.
